import Team2 from '../assets/images/projects_boetkkot_2024/team2.png';
import Team3 from '../assets/images/projects_boetkkot_2024/team3.png';
import Team4 from '../assets/images/projects_boetkkot_2024/team4.png';
import Team5 from '../assets/images/projects_boetkkot_2024/team5.png';
import Team6 from '../assets/images/projects_boetkkot_2024/team6.png';
import Team7 from '../assets/images/projects_boetkkot_2024/team7.png';
import Team8 from '../assets/images/projects_boetkkot_2024/team8.png';
import Team9 from '../assets/images/projects_boetkkot_2024/team9.png';
import Team10 from '../assets/images/projects_boetkkot_2024/team10.png';
import Team11 from '../assets/images/projects_boetkkot_2024/team11.png';
import Team12 from '../assets/images/projects_boetkkot_2024/team12.png';
import Team13 from '../assets/images/projects_boetkkot_2024/team13.png';
import Team14 from '../assets/images/projects_boetkkot_2024/team14.png';
import Team15 from '../assets/images/projects_boetkkot_2024/team15.png';
import Team16 from '../assets/images/projects_boetkkot_2024/team16.png';
import Team17 from '../assets/images/projects_boetkkot_2024/team17.png';
import Team18 from '../assets/images/projects_boetkkot_2024/team18.png';
import Team19 from '../assets/images/projects_boetkkot_2024/team19.png';
import Team20 from '../assets/images/projects_boetkkot_2024/team20.png';
import Team21 from '../assets/images/projects_boetkkot_2024/team21.png';
import Team22 from '../assets/images/projects_boetkkot_2024/team22.png';
import Team23 from '../assets/images/projects_boetkkot_2024/team23.png';
import Team24 from '../assets/images/projects_boetkkot_2024/team24.png';
import Team25 from '../assets/images/projects_boetkkot_2024/team25.png';
import Team26 from '../assets/images/projects_boetkkot_2024/team26.png';
import Team27 from '../assets/images/projects_boetkkot_2024/team27.png';
import Team28 from '../assets/images/projects_boetkkot_2024/team28.png';
import Team29 from '../assets/images/projects_boetkkot_2024/team29.png';
import Team30 from '../assets/images/projects_boetkkot_2024/team30.png';
import Team31 from '../assets/images/projects_boetkkot_2024/team31.png';
import Team32 from '../assets/images/projects_boetkkot_2024/team32.png';
import Team33 from '../assets/images/projects_boetkkot_2024/team33.png';
import Team34 from '../assets/images/projects_boetkkot_2024/team34.png';
import Team35 from '../assets/images/projects_boetkkot_2024/team35.png';
import Team36 from '../assets/images/projects_boetkkot_2024/team36.png';
import Team37 from '../assets/images/projects_boetkkot_2024/team37.png';

const BeotkkotProject2024Data = [
  {
    award: '대상',
    title: '소동',
    content: '소상공인을 위한 마케팅 AI 파트너',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_27_BE_1',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_27_FE',
    releaseLink: 'https://sodong.pages.dev/',
    image: Team27,
    pm: '최시현',
    design: '최아리',
    frontend: ['이가영, 김유신'],
    backend: ['정찬호, 양채린'],
  },
  {
    award: '최우수상',
    title: '백곰: 백신아 곰아워!',
    content: '20대 백신 접종률 향상을 위한 백신 조회 및 추천 서비스',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_4_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_4_FE',
    releaseLink: 'https://vacgom.co.kr',
    image: Team4,
    pm: '김지은',
    design: '전예나',
    frontend: ['김민정, 오소현'],
    backend: ['변해빈, 성형주'],
  },
  {
    award: '최우수상',
    title: '발표몇분',
    content: '발표가 쉬워진다. 발표몇분!',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_32_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_32_FE',
    releaseLink: 'https://www.balpyo.site/ (랜딩페이지, 안드로이드앱 개발)',
    image: Team32,
    pm: '김다원',
    design: '윤예빈',
    frontend: ['피유진, 진지현'],
    backend: ['김준식, 이동헌'],
  },
  {
    award: '우수상',
    title: '봄멍',
    content: '유기견을 관심있게 바라볼 수 있는 새로운 입양 서비스',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE',
    releaseLink: '',
    image: Team9,
    pm: '정민지',
    design: '이지혜',
    frontend: ['황현정, 여은동'],
    backend: ['권보궁, 김나령'],
  },
  {
    award: '우수상',
    title: '스타트업밸리',
    content: '사이드 프로젝트 협업 툴, 스타트업 밸리',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_28_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_28_FE',
    releaseLink: 'https://client.startupvalley.site/',
    image: Team28,
    pm: '김영원',
    design: '안재윤',
    frontend: ['정아현'],
    backend: ['임정우, 최정흠'],
  },
  {
    award: '',
    title: '먹킷리스트',
    content: '대학교 주변 맛집을 위주로 나만의 먹킷리스트를 작성할 수 있는 앱입니다.',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_2_BE_1',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_2_FE',
    releaseLink: '',
    image: Team2,
    pm: '김아현',
    design: '김도희',
    frontend: ['서재흔, 이경민'],
    backend: ['김우현, 서건혁'],
  },
  {
    award: '',
    title: '학사모',
    content: '한 곳에서 학교와 학과의 공지와 정보, 이벤트를 확인하는 서비스',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_3_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_3_FE_1',
    releaseLink: '',
    image: Team3,
    pm: '염경록',
    design: '정유리',
    frontend: ['이가은, 김성민'],
    backend: ['이재표, 유창호'],
  },
  {
    award: '',
    title: 'distance',
    content: '대학축제 1:1 랜덤 매칭 서비스',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_5_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_5_FE',
    releaseLink: 'dis-tance.com',
    image: Team5,
    pm: '김상훈',
    design: '김나영',
    frontend: ['노주영, 박솔미'],
    backend: ['김혜은, 이준석'],
  },
  {
    award: '',
    title: 'RESET',
    content: '게이미피케이션을 도입한 재활용 교육앱입니다',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_6_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_6_FE',
    releaseLink: '',
    image: Team6,
    pm: '이도형',
    design: '오세인',
    frontend: ['김세연, 허영현'],
    backend: ['손형준, 강효정'],
  },
  {
    award: '',
    title: '스터디메이트',
    content: '스터디, 멘토링 매칭 플랫폼',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_7_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_7_FE',
    releaseLink: '',
    image: Team7,
    pm: '진휘웅',
    design: '양다희',
    frontend: ['권인우, 조인식'],
    backend: ['김정호, 정은희'],
  },
  {
    award: '',
    title: '걱정보관함',
    content:
      '걱정보관함은 일상 생활에서 불쑥 찾아오는 걱정들을 보관해두고 걱정 시간에 꺼내봄으로써 현재에 집중하고 감정과 건강하게 마주할 수 있도록 지원하는 서비스입니다.',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_8_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_8_FE',
    releaseLink: 'https://worry-box.vercel.app/',
    image: Team8,
    pm: '조예진',
    design: '기도은',
    frontend: ['임하림, 이소윤'],
    backend: ['정조은, 최인호'],
  },
  {
    award: '',
    title: 'CEN',
    content: '당신만을 위한 맞춤형 장학금 서비스, cen으로 concentrate하세요!',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_10_BE_EXPRESS',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_10_FE/tree/main',
    releaseLink: '',
    image: Team10,
    pm: '김솔',
    design: '조예진',
    frontend: ['김민솔, 정성윤'],
    backend: ['장성원, 한다은'],
  },
  {
    award: '',
    title: '이츠타임',
    content: '모두의 밥약을 하나에 모으다, 이츠타임',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_11_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_11_FE',
    releaseLink: 'https://eatstime.vercel.app/',
    image: Team11,
    pm: '박지환',
    design: '유지희',
    frontend: ['김현아, 김경재'],
    backend: ['김남기, 문성욱'],
  },
  {
    award: '',
    title: 'WEAR',
    content: '대학생을 위한 기부 & 중고 거래 플랫폼',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_12_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_12_FE',
    releaseLink: '',
    image: Team12,
    pm: '박수빈',
    design: '김서영',
    frontend: ['김동균, 안정민'],
    backend: ['박미정, 진미나'],
  },
  {
    award: '',
    title: 'N분의 1',
    content: '식재료 공동구매 서비스',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_13_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_13_FE',
    releaseLink: 'https://n1.junyeong.dev',
    image: Team13,
    pm: '김도훈',
    design: '이민우',
    frontend: ['김유진, 박나리'],
    backend: ['윤준영, 김수현'],
  },
  {
    award: '',
    title: 'Plan Death',
    content: '나의 내일을 기획하세요',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_14_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_14_FE',
    releaseLink: 'https://plandeath.site/',
    image: Team14,
    pm: '송효재',
    design: '강지수',
    frontend: ['민유빈, 이세민'],
    backend: ['장우림, 조예빈'],
  },
  {
    award: '',
    title: '가정통신문',
    content: '대학생들의 효율적인 의사소통을 위한 서비스',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_15_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_15_FE',
    releaseLink: 'https://goormnotification.vercel.app/',
    image: Team15,
    pm: '김지은',
    design: '전세원',
    frontend: ['고민지, 최재영'],
    backend: ['김지민, 사현진'],
  },
  {
    award: '',
    title: '탐험하장!',
    content:
      '전통 시장의 가치를 재조명하다, 즐거운 시장 모험 속 ‘유대감’으로 상인과 소비자를 연결하는 서비스 탐험하장! 입니다.',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_16_BE.git',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_16_FE.git',
    releaseLink: '',
    image: Team16,
    pm: '마소영',
    design: '나지완',
    frontend: ['김동현, 김다은'],
    backend: ['박종범, 임수한'],
  },
  {
    award: '',
    title: 'PONNECT',
    content: '특별한 커스텀 명함을 만드는 대학생 명함 지갑 서비스',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_17_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_17_FE.git',
    releaseLink: 'https://ponnect.netlify.app',
    image: Team17,
    pm: '윤서연',
    design: '윤예원',
    frontend: ['송민석, 김서윤'],
    backend: ['이은정, 최현영'],
  },
  {
    award: '',
    title: '헤쳐모여!',
    content: '청소년들이 안전하고 건전한 커뮤니티에서 유대감을 형성하여 소외감을 최소화',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_18_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_18_FE',
    releaseLink: '',
    image: Team18,
    pm: '',
    design: '황은비',
    frontend: ['홍창기, 한승연'],
    backend: ['김중현, 오정빈'],
  },
  {
    award: '',
    title: '원해빗',
    content: '하나의 습관이 모여 나를 이룬다, 꾸준한 습관 만들기 원해빗',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_19_FE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_19_BE',
    releaseLink: 'https://want-habit.vercel.app/',
    image: Team19,
    pm: '',
    design: '강채민',
    frontend: ['봉지수, 박제준'],
    backend: ['진승현, 임장혁'],
  },
  {
    award: '',
    title: '큐터디(Qtudy)!?',
    content: '함께 성장하는 AI 스터디 메이트',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_20_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_20_FE.git',
    releaseLink: 'https://qtudy.site',
    image: Team20,
    pm: '은세윤',
    design: '김다혜',
    frontend: ['홍서영'],
    backend: ['한채은, 김예서'],
  },
  {
    award: '',
    title: '팀크루즈',
    content: '카카오 esg 경영 팀 빌딩 증진 프로젝트',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_21_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_21_FE',
    releaseLink: 'http://teamkrews-front-bucket.s3-website.ap-northeast-2.amazonaws.com/',
    image: Team21,
    pm: '김하영',
    design: '이주희',
    frontend: ['신아진, 노승희'],
    backend: ['김승언, 이유재'],
  },
  {
    award: '',
    title: '집안일 요정',
    content: '자취? 집안일 요정이 다 알려줄게!',
    backendLink:
      'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_Thttps://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_22_BEEAM_22_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_22_FE',
    releaseLink: '',
    image: Team22,
    pm: '김민지',
    design: '고영주',
    frontend: ['김정주, 노욱진'],
    backend: ['박예원, 김채흔'],
  },
  {
    award: '',
    title: '자니…?',
    content: '밤샘러들을 위한 밤샘메이트 서비스',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_23_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_23_FE',
    releaseLink: 'https://dongkyeom.com',
    image: Team23,
    pm: '김보정',
    design: '최지원',
    frontend: ['강석호, 정도현'],
    backend: ['이다은, 장동겸'],
  },
  {
    award: '',
    title: 'REINPUT',
    content: 'One-Stop 자동화 아카이빙 및 리마인더 서비스',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_24_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_24_FE',
    releaseLink: 'https://2024-beotkkotthon-team-24-fe.vercel.app/',
    image: Team24,
    pm: '이은주',
    design: '양민설',
    frontend: ['한우준, 곽수정'],
    backend: ['조현성, 장민호'],
  },
  {
    award: '',
    title: '온지구',
    content: '매일 환경 보호 미션으로 꾸미는 나의 지구',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_25_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_25_FE',
    releaseLink: '',
    image: Team25,
    pm: '최지민',
    design: '이한별',
    frontend: ['김민지, 이재윤'],
    backend: ['김시원, 엄기훈'],
  },
  {
    award: '',
    title: '식(食)스팩',
    content: '모두가 잘먹고 잘 살 수밖에 없는로컬 식당 (F&B)성장지원 플랫폼',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_26_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_26_FE',
    releaseLink: '',
    image: Team26,
    pm: '이민우',
    design: '이주성',
    frontend: ['권지민, 김윤섭'],
    backend: ['김건, 이원빈'],
  },

  {
    award: '',
    title: 'tomaDo!',
    content: '당신만의 집중력 도우미!',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_29_BE.git',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_29_FE.git',
    releaseLink: '',
    image: Team29,
    pm: '김수영',
    design: '이아영',
    frontend: ['최규원, 이하빈'],
    backend: ['박소연, 신주은'],
  },
  {
    award: '',
    title: '비하인드유',
    content: '청각장애인을 위한 소리 판별 서비스',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_30_AI',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_30_FE',
    releaseLink: '',
    image: Team30,
    pm: '양민지',
    design: '이정향',
    frontend: ['구예원, 김유정'],
    backend: ['최효정, 오규혁'],
  },
  {
    award: '',
    title: '브레인스낵',
    content: '취준생을 위한 인적성 검사 준비 솔루션, 브레인스낵',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_31_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_31_FE',
    releaseLink: 'http://d2hzeg1hy2crop.cloudfront.net',
    image: Team31,
    pm: '구나연',
    design: '최준형',
    frontend: ['강어진, 박지원'],
    backend: ['김지원, 이현석'],
  },

  {
    award: '',
    title: '기억해봄',
    content: '음성으로 사진에 이야기를 남기는 AI 사진일기 서비스',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_33_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_33_FE',
    releaseLink: 'https://www.re-bom.shop',
    image: Team33,
    pm: '나윤주',
    design: '한예은',
    frontend: ['이승현, 박재현'],
    backend: ['정연재, 최기웅'],
  },
  {
    award: '',
    title: 'KKIRI',
    content: '우리끼리 돌고도는 도움 교환 서비스',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_34_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_34_FE/tree/main',
    releaseLink: '',
    image: Team34,
    pm: '정지윤',
    design: '장혜린',
    frontend: ['장민수, 박지원'],
    backend: ['이호연, 심재윤'],
  },
  {
    award: '',
    title: '돈버니(돈bunny)',
    content: '돈을 버는 토끼의 애칭처럼 친근하게, 대학생 금융 교육 및 재정적 부담을 줄여주는 서비스',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_35_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_35_FE',
    releaseLink: 'https://2024-beotkkotthon-team-35-fe-sigma.vercel.app/',
    image: Team35,
    pm: '이예은',
    design: '김유림',
    frontend: ['황세윤, 안봉근'],
    backend: ['윤덕건, 김성민'],
  },
  {
    award: '',
    title: '매일,메일',
    content: '새로운 세상의 문턱에서,당신만의 지원군이 되어드리는 "이메일 작성 치트키',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_36_BE',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_36_FE',
    releaseLink: 'https://maeilmail.store/',
    image: Team36,
    pm: '정세린',
    design: '전한나',
    frontend: ['김다윤, 이재욱'],
    backend: ['강연수, 심훈'],
  },
  {
    award: '',
    title: '댓칼코마니',
    content:
      '댓칼코마니는 댓글 중 유해 요소를 걸러내고 유익한 피드백만을 제공하여 작가의 창작 활동을 보호하고 증진시키는 서비스입니다.',
    backendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_37_BE.git',
    frontendLink: 'https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_37_FE.git',
    releaseLink: 'https://2024-beotkkotthon-team-37-fe.vercel.app/',
    image: Team37,
    pm: '정윤서',
    design: '성나영',
    frontend: ['이준원, 이종법, 이태환'],
    backend: ['황채원, 최윤서'],
  },
];

export default BeotkkotProject2024Data;
