import Team1 from '../assets/images/projects/team1.png';
import Team2 from '../assets/images/projects/team2.png';
import Team3 from '../assets/images/projects/team3.png';
import Team4 from '../assets/images/projects/team4.png';
import Team5 from '../assets/images/projects/team5.png';
import Team6 from '../assets/images/projects/team6.png';
import Team7 from '../assets/images/projects/team7.png';
import Team8 from '../assets/images/projects/team8.png';
import Team9 from '../assets/images/projects/team9.png';
import Team10 from '../assets/images/projects/team10.png';
import Team11 from '../assets/images/projects/team11.png';
import Team12 from '../assets/images/projects/team12.png';
import Team13 from '../assets/images/projects/team13.png';
import Team14 from '../assets/images/projects/team14.png';
// https://eunbeann.notion.site/eunbeann/9e3f7b4ecd9e4566a49370ad34dd9409
const DanpoongProject2023Data = [
  {
    award: '대상',
    title: '무코(mooco)',
    content: '일상의 순간들을 담은 바코드아트를 제공하는 웹서비스',
    backendLink: 'https://github.com/goormthon-Univ/TEAM_7_2',
    frontendLink: 'https://github.com/goormthon-Univ/TEAM_7',
    releaseLink: '',
    image: Team7,
    pm: '노윤진',
    design: '최재훈',
    frontend: ['오찬주', '진지현', '정은지'],
    backend: ['강승준', '김미소'],
  },
  {
    award: '최우수상',
    title: '마이쿠키하우스',
    content: '1년을 사진으로 기억하는 추억 회고 서비스',
    backendLink: 'https://github.com/goormthon-Univ/TEAM_13_2',
    frontendLink: 'https://github.com/goormthon-Univ/TEAM_13',
    releaseLink: 'https://www.cookiehouse.site',
    image: Team13,
    pm: '육혜지',
    design: '양정민',
    frontend: ['김민성', '황태환', '오민지'],
    backend: ['조예빈', '오동재'],
  },
  {
    award: '우수상',
    title: 'Floud',
    content: '지나간 자리에 남는 비행운처럼, 성장의 자취를 기록하고 공유하는 회고 모바일 웹서비스.',
    backendLink: 'https://github.com/goormthon-Univ/TEAM_2_BE',
    frontendLink: 'https://github.com/goormthon-Univ/TEAM_2_2',
    releaseLink: 'https://www.floud.site/',
    image: Team2,
    pm: '양나은',
    design: '정민지',
    frontend: ['조민규', '민유빈'],
    backend: ['김성준', '강연수'],
  },
  {
    award: '우수상',
    title: '구름멍',
    content: '펫로스 증후군 극복을 위한 추억 아카이빙 및 소통 서비스, 구름멍!',
    backendLink: 'https://github.com/goormthon-Univ/TEAM_8_2_BE',
    frontendLink: 'https://github.com/goormthon-Univ/TEAM_8',
    releaseLink: 'https://team-8-iota.vercel.app/Login/',
    image: Team8,
    pm: '조하은',
    design: '정희경',
    frontend: ['이나경', '이진우'],
    backend: ['최기웅', '신서연'],
  },
  {
    title: 'Seasoning(시즈닝)',
    content: '24절기로 기록하는 1년, 한해를 기록하는 나만의 방식',
    backendLink: 'https://github.com/goormthon-Univ/TEAM_1',
    frontendLink: 'https://github.com/goormthon-Univ/TEAM_1_2',
    releaseLink: '',
    image: Team1,
    pm: '김수영',
    design: '강승현',
    frontend: ['최어진', '이세민'],
    backend: ['김동철', '이아린'],
  },
  {
    title: 'AllerGenie',
    content: '약에 대한 정보를 한눈에 파악하는 서비스',
    backendLink: 'https://github.com/goormthon-Univ/TEAM_3',
    frontendLink: 'https://github.com/goormthon-Univ/TEAM_3_2',
    releaseLink: '',
    image: Team3,
    pm: '박규원',
    design: '김지은',
    frontend: ['김수현', '사공광열'],
    backend: ['조예지', '이윤서'],
  },
  {
    title: '뜬구름',
    content:
      '‘뜬구름’은 당신의 뜬구름잡는 생각, 고민, 아이디어 등을 메모해두었다가 타래를 적어가며 발전시킬 수 있는 서비스입니다. 거기에, 소중한 생각을 당신이 잊어버리지 않도록 알림도 보내드려요.',
    backendLink: 'https://github.com/goormthon-Univ/TEAM_4_BE.git',
    frontendLink: 'https://github.com/goormthon-Univ/TEAM_4.git',
    releaseLink: 'www.ddngoorm.xyz',
    image: Team4,
    pm: '최윤서',
    design: '박현서',
    frontend: ['홍민우', '박시현'],
    backend: ['이선의'],
  },
  {
    title: '아고라',
    content: '독서 모임 운영, 발제문 기록, 우리 모임의 역사를 한번에 정리할 수 있는 독서 모임 운영 웹 서비스',
    backendLink: 'https://github.com/goormthon-Univ/TEAM_5_BE',
    frontendLink: 'https://github.com/goormthon-Univ/TEAM_5',
    releaseLink: '',
    image: Team5,
    pm: '박신형',
    design: '정유리',
    frontend: ['한슬희', '김혜진'],
    backend: ['이강희', '김예린'],
  },
  {
    title: '구름처럼',
    content: '구름이 만들어지는 과정처럼, 당신의 목표를 이룰 수 있게 도와주는 서비스 ‘구름처럼’',
    backendLink: 'https://github.com/goormthon-Univ/TEAM_6_BE',
    frontendLink: 'https://github.com/goormthon-Univ/TEAM_6',
    releaseLink: 'https://like-a-cloud.netlify.app/',
    image: Team6,
    pm: '윤승지',
    design: '박혜연',
    frontend: ['김세훈', '이지원'],
    backend: ['이서연', '신정윤'],
  },
  {
    title: 'SeasonWell(시즌웰)',
    content: '계절에 따른 질병에 대한 의약품과 건강 관리 방법을 안내하는 서비스',
    backendLink: 'https://github.com/goormthon-Univ/TEAM_9_2',
    frontendLink: 'https://github.com/goormthon-Univ/TEAM_7',
    releaseLink: 'https://moodbarcode.com/',
    image: Team9,
    pm: '정다운',
    design: '임채현',
    frontend: ['박병영', '이근우', '한기종'],
    backend: ['주현정', '이정현'],
  },
  {
    title: '구르모아',
    content: '말풍선의 구름 모양을 활용한 모임 SNS ‘구르모아’',
    backendLink: 'https://github.com/goormthon-Univ/TEAM_10_2',
    frontendLink: 'https://github.com/goormthon-Univ/TEAM_10',
    releaseLink: '',
    image: Team10,
    pm: '성준일',
    design: '임서현',
    frontend: ['박민석', '김윤서'],
    backend: ['김정목', '홍성주'],
  },
  {
    title: '구름이 전해주는 편지',
    content: '전하지 못했던 마음을 다양한 구름의 특성을 이용해 전해주는 웹 서비스 ‘구름이 전해주는 편지’',
    backendLink: 'https://github.com/goormthon-Univ/TEAM_11_2',
    frontendLink: 'https://github.com/goormthon-Univ/TEAM_11',
    releaseLink: '',
    image: Team11,
    pm: '곽호은',
    design: '김가은',
    frontend: ['나혜인', '김채현'],
    backend: ['김현우', '강민서'],
  },
  {
    title: '가치 구름',
    content: ' 협업 기록을 통한 구름 키우기 서비스',
    backendLink: 'https://github.com/goormthon-Univ/TEAM_12_2',
    frontendLink: 'https://github.com/goormthon-Univ/TEAM_12',
    releaseLink: '',
    image: Team12,
    pm: '강민주',
    design: '심서현',
    frontend: ['신유수', '박철민'],
    backend: ['이종범', '강희진'],
  },
  {
    title: '오늘의 구름 (’오구’)',
    content: '‘오늘의 구름’은 나의 하루를 감정구름으로 나타내는 감성 일기 기록 서비스',
    backendLink: 'https://github.com/goormthon-Univ/TEAM_14',
    frontendLink: 'https://github.com/goormthon-Univ/TEAM_14_2',
    releaseLink: '',
    image: Team14,
    pm: '이유조',
    design: '남연우',
    frontend: ['이유민', '윤지수'],
    backend: ['조승빈', '박소정'],
  },
];

export default DanpoongProject2023Data;
